### ISSUE TITLE
Bitbucket option

### ISSUE THREAD

**Issue by 16n** [btford/grunt-conventional-changelog#18]
Hi 

I really like your module but in my company we do not use github.
Due to the fact that we use bitbucket, the links in the generated changelog do not work.
I forked the project and implemented a bitbucket option (https://github.com/daseinhorn/grunt-conventional-changelog). Do you have any interest in a pull request?

Thanks,
Das Einhorn

**Comment by eknowles** [comment]
I think this should be reopened as the bitbucket markdown doesn't support the nested lists
https://bitbucket.org/tutorials/markdowndemo

In Github it looks fine like

```
* thing 0
* thing 1
  *thing 1.1
* thing 2
```
where as bitbucket is

```
* thing 0
+ thing 1 <-- uses plus symbol +
    *thing 1.1 <-- 4 spaces indent
* thing 2
```
thoughts?

**Comment by brunobatista** [comment]
+1
