### ISSUE TITLE
missing full coverage suite

### ISSUE THREAD

**Issue by stevemao** [btford/grunt-conventional-changelog#43]

**Comment by eddiemonge** [comment]
more than this "full coverage suite"? https://github.com/btford/grunt-conventional-changelog/blob/master/test/test.js

**Comment by stevemao** [comment]
Not sure how to test this grunt wrapper. I guess as long as it loads the module properly it should be fine. Since this is not a "multi task" I can't simply generate another temporary changelog in `tmp` folder. And the `changelog` task is already doing `release` task.
