### ISSUE TITLE
Usage.

### ISSUE THREAD

**Issue by blowsie** [btford/grunt-conventional-changelog#46]
At what point in time should someone run the changelog task? I'm rather confused.

Maybe its one of the following;
 - Before a version bump
 - After a version bump
 - Before a commit
 - After a commit

I also have an issue where the task is parsing all of the valid commits, not ones since the last tag.

My process currently is;
- Make changes
- Bump
- Tag
- Commit
- grunt changelog

Any guidance would be great, perhaps I can add it do your documentation

**Comment by stevemao** [comment]
I think before a version bump would be good. Have a look at angular.js or angular related projects as examples.

**Comment by blowsie** [comment]
Thank I will take a look at those, It would we be great to add something to the documentation

**Comment by blowsie** [comment]
Reopening, every time I update the changelog, it adds all commits, not just the once since last tag.
Any idea why this might be happening?

**Comment by eddiemonge** [comment]
It should be:

* Make changes
* Commit those changes
* Bump
* grunt changelog
* Commit
* Tag

**Comment by eddiemonge** [comment]
if that fails, open an issue at https://github.com/ajoslin/conventional-changelog since this is a wrapper around that.
