### ISSUE TITLE
Template for CHANGELOG.md

### ISSUE THREAD

**Issue by brunobatista** [btford/grunt-conventional-changelog#47]
Will be nicer if have possibility to change CHANGELOG template.

```js
    // Creates a changelog on a new version
    changelog: {
      options: {
        dest: 'CHANGELOG.md',
        template: 'changelog.tpl'
      }
    }
```

**Comment by pkozlowski-opensource** [comment]
I think it should be handled in the https://github.com/ajoslin/conventional-changelog. There are already requests in there to support different output formatting (ex. https://github.com/ajoslin/conventional-changelog/issues/35) but IMO we should have a more generic solution - https://github.com/ajoslin/conventional-changelog/issues/22

**Comment by brunobatista** [comment]
Nice. Thanls @pkozlowski-opensource :+1:

**Comment by stevemao** [comment]
Please checkout the rewrite on the master branch and see if the problem still exists. Thanks.
