### ISSUE TITLE
shortcut repository url format

### ISSUE THREAD

**Issue by marcin-wosinek** [btford/grunt-conventional-changelog#48]
`getPackageRepository` parse repository form package.json, but doesn't take into account npm's shortcut syntax for git repositories. I've raised that in https://github.com/ajoslin/conventional-changelog/issues/37 earlier, but looks that this should be solved here.

I will try to prepare PR in a free time.

**Comment by stevemao** [comment]
This will be fixed in https://github.com/ajoslin/conventional-changelog/pull/38

**Comment by marcin-wosinek** [comment]
Great, thanks a lot:)
