### ISSUE TITLE
use `core.editor` from git as editior option

### ISSUE THREAD

**Issue by yfr** [btford/grunt-conventional-changelog#49]
Is there a way to use the git editor (or maybe `$VISUAL` or `$EDITOR`) as a default for the editor option?

We use different editors in our office and i don't want to predefine/commit the config with an editor only i use. So it would be nice to have an option to use ENV or something like `git config core.editor`.

**Comment by yfr** [comment]
Just found something working:

```js
  options: {
    editor: '`git config core.editor`'
  }
```

But maybe there is a better way to do this.

**Comment by stevemao** [comment]
This could be an additional feature of https://github.com/btford/grunt-conventional-changelog/pull/35

**Comment by stevemao** [comment]
Please use [grunt-shell](https://github.com/sindresorhus/grunt-shell) instead.
