### ISSUE TITLE
`options.prepend` doesn't do anything

### ISSUE THREAD

**Issue by stevemao** [btford/grunt-conventional-changelog#50]
`options.prepend` was removed with out any notification in caa14d694ed14b0ec322e85533cf4e350136e50. Do we still want to keep this feature? Or maybe we should come up a more generic solution for https://github.com/ajoslin/conventional-changelog/issues/22

**Comment by brunobatista** [comment]
+1

**Comment by stevemao** [comment]
Please checkout the rewrite on the master branch on `conventional-changelog` and see if the problem still exists. Thanks.
