### ISSUE TITLE
Can we make a minor release?

### ISSUE THREAD

**Issue by stevemao** [btford/grunt-conventional-changelog#52]
cc @btford , there are some bug fixed and more logics are moved to `conventional-changelog`.

There is no public api changes

If everything seems fine with you can you make a minor release?

Also can you enable travis on https://travis-ci.org please? Thanks.

Currently I'm trying to split conventional-changelog into smaller modules.

**Comment by btford** [comment]
done.

Sure, feel free to release once Travis is green. Let me know if you need anything else.

**Comment by stevemao** [comment]
Thanks @btford , are you happy with the current code? Also decisions like deprecating `options.editor` in favour of `grunt-shell`?

**Comment by btford** [comment]
I am, but let me ask @passy and @sindresorhus, who are probably more picky than I.

**Comment by stevemao** [comment]
cc @eddiemonge

**Comment by eddiemonge** [comment]
I'm in favor of "Also decisions like deprecating options.editor in favour of grunt-shell" but it sounds like it wasn't blocking?

**Comment by eddiemonge** [comment]
@btford npm permissions?

**Comment by stevemao** [comment]
Sorry, what do you mean by "it sounds like it wasn't blocking?"

**Comment by stevemao** [comment]
If all agree I will add a warning message in task if people are trying to use `options.editor`

**Comment by eddiemonge** [comment]
I mean someone complained that opening grunt-shell instead of the editor command here opened the changelog but grunt kept going with other tasks

**Comment by stevemao** [comment]
ah, didn't realise this problem.

35a92b1d4d30b72d26e4238f311962529f29567f commit message should include this as a breaking change.

I agree this needs to be solved before we deprecate `options.editor`

**Comment by stevemao** [comment]
Just test, it doesn't have the problem.

**Comment by stevemao** [comment]
Hi @btford , I'm quite happy with the current code and docs now. Would you like to give me npm permission? Or you can just publish it (don't forget to generate a changelog and add a release tag). 

My npm username is : `stevemao`

Thanks.

**Comment by stevemao** [comment]
ping @btford

**Comment by AleksueiR** [comment]
:+1:

**Comment by stevemao** [comment]
ping @btford

**Comment by btford** [comment]
sorry for the delay!!

you should be added now.

**Comment by stevemao** [comment]
Thank you :dancer:
