### ISSUE TITLE
Bug Missing = sign

### ISSUE THREAD

**Issue by andre-ferreira-qlik** [btford/grunt-conventional-changelog#54]
From my configuration of:
```js
  grunt.config('changelog', {
    options : {
      file : "../CHANGELOG.md",
      dest : "..CHANGELOG.md"
    }
  });
```
I get the following output
<a name"0.1.17"></a>
... etc

Mind the missing = sign between name and the quote

**Comment by andre-ferreira-qlik** [comment]
Possibly this would leave better in the "conventional-changelog".
Bug on line 115 of the Writer.js

**Comment by stevemao** [comment]
Can you be a bit more specific? What's `dest : "..CHANGELOG.md"` doing here?

**Comment by stevemao** [comment]
Can you provide a minimum detailed procedure how to replicate this? Thanks. Also *Issues with the output should be reported on the `conventional-changelog` [issue tracker](https://github.com/ajoslin/conventional-changelog/issues).*

**Comment by andre-ferreira-qlik** [comment]
dest was a copy past error, it should read ../, i've tried both has i was unsure of the difference.
The problem i was reporting was masked by the Github issue has the html returned should be:

I get the following output
< a name"0.1.17" >< / a >
... etc
a the missing = sign between name and the quote is/was my report

**Comment by stevemao** [comment]
did you mean:
Expected:
```html
< a name="0.1.17" >< / a >
```
But got
```html
< a name"0.1.17" >< / a >
```
This is fixed in https://github.com/stevemao/conventional-commits-writer and is waiting on https://github.com/ajoslin/conventional-changelog/pull/51

**Comment by andre-ferreira-qlik** [comment]
That's exactly it. Thank you
