### ISSUE TITLE
options.dest is ignored

### ISSUE THREAD

**Issue by drichard** [btford/grunt-conventional-changelog#55]
The `dest` option is not working anymore and it always defaults to 'CHANGELOG.md'.
As a workaround, you can use the `file` option which does the same.

This bug is caused by changelog.js:

````
var options = this.options({
      file: 'CHANGELOG.md',
     [...]
    });
options.file = options.file || options.dest;
````

You can see how `options.file` is always truthy and `options.dest` will therefore be ignored.

**Comment by stevemao** [comment]
PR welcome :+1:

**Comment by stevemao** [comment]
ping @drichard
