### ISSUE TITLE
What happened to `validate-commit-msg.js`

### ISSUE THREAD

**Issue by Dignifiedquire** [btford/grunt-conventional-changelog#56]
In karma we used `validate-commit-msg.js` as a git precommit hook, but sadly it's gone from this repo and I couldn't find it in conventional-changelog either. Was it moved to an independent module or do we have to maintain our own version now?

Ref https://github.com/karma-runner/karma/issues/1457

**Comment by stevemao** [comment]
I don't know, I don't think it should be here. Did you search in the angular repo? @btford might know?

**Comment by stevemao** [comment]
Closing as this is not an actual "issue" here. Wish you find the it @Dignifiedquire !
