### ISSUE TITLE
Having issues with slashes in scope

### ISSUE THREAD

**Issue by ivanbreet** [btford/grunt-conventional-changelog#57]
Hi,

It appears that grunt-conventional-changelog misses all commits with a "/" in scope (`<type>(<scope>): <subject>`).

Example commit messages affected:
- feat(**api/user**): add support for OAuth2
- fix(**api/v1**): fix local API limit

..but the following does work:
- feat(**user**): add support for OAuth2

Renaming all commits just to use this tool isn't an option. Any help/advise would be greatly appreciated.

**Comment by stevemao** [comment]
this should fixed in the alpha of conventional-changelog, can you try 
```
$ npm install conventional-changelog@next
```
Also *Issues with the output should be reported on the conventional-changelog issue tracker.* Thanks.
