### ISSUE TITLE
Cannot name change log task 'changelog', must call it 'conventionalChangelog'

### ISSUE THREAD

**Issue by marco-faustinelli** [btford/grunt-conventional-changelog#60]
I am using version 4.1.0. I define the change log task inside Gruntfile.js and name it 'changelog'.

Then I run `grunt changelog`. Reply from the system is: 'Task changelog not found', but the task is there...

Then  I rename the task to 'conventionalChangelog' and run `grunt conventionalChangelog`. Everything runs just fine.

I've verified that also che following names are not good for my task, and all fail with message `task xxx not found`

- cohangelog

- change_log

The only reason I'm asking is because https://github.com/buildfirst/buildfirst/tree/master/ch04/04_conventional-changelog apparently can use the shorter task name.

**Comment by stevemao** [comment]
I don't get what your problem is. The task name is `conventionalChangelog`, same as the module name.

**Comment by stevemao** [comment]
I think I understand you now. You should probably open an issue there :)

**Comment by stevemao** [comment]
@marco-faustinelli https://github.com/buildfirst/buildfirst/pull/28
