### ISSUE TITLE
Suggested improvement to Readmemd

### ISSUE THREAD

**Issue by uglow** [btford/grunt-conventional-changelog#61]
It took me about 15 minutes to figure out where to put my host details. Previously I just pointed it to the `package.json`'s `repository.url` property and it worked.

So this example, showing where to put the host and repository name, may help others too:
```
options: {
  changelogOpts: {
    // conventional-changelog options go here
    preset: 'angular'
  },
  context: {
    host: 'https://somehost',
    repository: 'company/repo-name'
  }
}
```

This is required to generate the links to the commits in the changelog file

**Comment by stevemao** [comment]
merge with https://github.com/ajoslin/conventional-changelog/issues/98

**Comment by stevemao** [comment]
The module should still read package.json
the examples are in conventional-changelog and we provide a link here so we don't have to write the same thing twice. If you think the docs are still confusing please send a PR.
